language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
  - secure: pGJ0XuRmxWryc5R4zTDjgQuU2Lyt+irF231ya8BB7sCcebtPvSLIikDAUoJ7/U1oYjqtpXPBrMlQIWkUM3TJKL7iyov1N2rShFdFfk8hOm8Tvok5fYBcEmwuNOgL6PjEBqbcKfJ1i3zfV+u57LW7ukjDdp6H4z/WM8znwSgq2QtDvmxjfgon/GtJaLPXPwZG4Zq88oqPOpkeP0pT3RkbHg2NM8Fnq17vthZR0BcFjYNJuXRjjZb5CsCtXNKmbOMIfa9LGtcTwKE5D/8eViBIvPbZfqomrPgCr1gmiuH0uvOL7/v87W3FQoXQvn/k1VcnTnSBPjDx1AhNQXxaY7ppELsCBIxhfCGzfSJ+T5/4dqwuenADCDjRt4GrTJw6Y4Op7TMzegV/yvEvF/jD+WfUbUC1tg3YMZTEJmPjCfDe6o3/14+x+HhVGrmv/RyOOrNHtbWZD9VVAz1gJOrDi2Z0pyme+Pn1E6soSShMv/iPWnTdG6jywZsXrf56gjdmyfLeso0cU7VkphvlDaRlNsWP0QCaohNiMPT2BzYnh1r387icIBNhhmbB4KExdOgnJfWyQJW7wQGxMUg/JaxCp8th5xuq4guQ2+UGdZQey17ujjx3E/+ihu/oPVmUDLp4bxUfRfVVs2mRrPYKCOY/4YfUomrty/JtwdXIAg9D++iMp/8=
