# Site settings
# http://jekyllrb.com/docs/configuration/
title: Steve Moser
email: # TODO: Replace with contact form
description: > 
  iOS Developer. Bikeshedder. Functionalist. Semantist. Wash. Rinse. Repeat.
baseurl: "/stevemoser.org.old" # the subpath of your site, e.g. /blog
permalink: posts/:title
url: "http://stevemoser.org" # the base hostname & protocol for your site
twitter_username: stevemoser
github_username:  stevemoser

# Build settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
include: ['_pages']
exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Rakefile']
markdown: redcarpet # more like github - http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
